

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CASA
 */
public class Interfaz extends javax.swing.JFrame {
    Client client = new Client();
    //client.initClient();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameColores = new javax.swing.JFrame();
        botonRojo = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonDesconectar = new javax.swing.JButton();
        frameTickets = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTickets = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosTicket = new javax.swing.JTextArea();
        botonAtender = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cronometro = new javax.swing.JDialog();
        Reanudar = new javax.swing.JButton();
        Pausar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonAtendido = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        frameSinExito = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botonEnviarSinExito = new javax.swing.JButton();
        datosTicketListo = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        botonDatosEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        frameLogIn = new javax.swing.JButton();

        frameColores.setMinimumSize(new java.awt.Dimension(400, 300));

        botonRojo.setBackground(new java.awt.Color(255, 51, 51));
        botonRojo.setText("Rojo");
        botonRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRojoMouseClicked(evt);
            }
        });

        botonAmarillo.setBackground(new java.awt.Color(255, 255, 51));
        botonAmarillo.setText("Amarillo");
        botonAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmarilloMouseClicked(evt);
            }
        });

        botonVerde.setBackground(new java.awt.Color(153, 255, 0));
        botonVerde.setText("Verde");
        botonVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerdeMouseClicked(evt);
            }
        });

        jButton2.setText("Generar reporte");

        botonDesconectar.setText("Desconectar");
        botonDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDesconectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frameColoresLayout = new javax.swing.GroupLayout(frameColores.getContentPane());
        frameColores.getContentPane().setLayout(frameColoresLayout);
        frameColoresLayout.setHorizontalGroup(
            frameColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameColoresLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(frameColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(frameColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonDesconectar)
                .addContainerGap())
        );
        frameColoresLayout.setVerticalGroup(
            frameColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameColoresLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(frameColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(botonDesconectar))
                .addContainerGap())
        );

        frameTickets.setMinimumSize(new java.awt.Dimension(570, 350));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tickets pendientes");

        listTickets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ticket 1", "Ticket 2", "Ticket 3", "Ticket 4", "Ticket 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTickets.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTicketsMouseClicked(evt);
            }
        });
        listTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listTicketsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listTickets);

        jLabel3.setText("Datos del ticket:");

        datosTicket.setEditable(false);
        datosTicket.setColumns(20);
        datosTicket.setRows(5);
        jScrollPane2.setViewportView(datosTicket);

        botonAtender.setText("Atender ticket");
        botonAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtenderMouseClicked(evt);
            }
        });
        botonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtenderActionPerformed(evt);
            }
        });

        jButton1.setText("Refrescar");

        javax.swing.GroupLayout frameTicketsLayout = new javax.swing.GroupLayout(frameTickets.getContentPane());
        frameTickets.getContentPane().setLayout(frameTicketsLayout);
        frameTicketsLayout.setHorizontalGroup(
            frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTicketsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameTicketsLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(botonAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frameTicketsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameTicketsLayout.setVerticalGroup(
            frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTicketsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameTicketsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAtender)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Cronometro.setMinimumSize(new java.awt.Dimension(350, 300));

        Reanudar.setText("Reanudar");

        Pausar.setText("Pausar");
        Pausar.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabel4.setText("Cronómetro");

        botonAtendido.setText("Ticket atendido");
        botonAtendido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtendidoMouseClicked(evt);
            }
        });
        botonAtendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtendidoActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar ticket");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CronometroLayout = new javax.swing.GroupLayout(Cronometro.getContentPane());
        Cronometro.getContentPane().setLayout(CronometroLayout);
        CronometroLayout.setHorizontalGroup(
            CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CronometroLayout.createSequentialGroup()
                .addGroup(CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CronometroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Reanudar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CronometroLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        CronometroLayout.setVerticalGroup(
            CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CronometroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reanudar)
                    .addComponent(Pausar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CronometroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAtendido))
                .addGap(41, 41, 41))
        );

        frameSinExito.setMinimumSize(new java.awt.Dimension(518, 350));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Indique la razón por la cual abandona el ticket sin éxito:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        botonEnviarSinExito.setText("Enviar");
        botonEnviarSinExito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEnviarSinExitoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frameSinExitoLayout = new javax.swing.GroupLayout(frameSinExito.getContentPane());
        frameSinExito.getContentPane().setLayout(frameSinExitoLayout);
        frameSinExitoLayout.setHorizontalGroup(
            frameSinExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSinExitoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(frameSinExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEnviarSinExito)
                    .addGroup(frameSinExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        frameSinExitoLayout.setVerticalGroup(
            frameSinExitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSinExitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonEnviarSinExito)
                .addContainerGap())
        );

        datosTicketListo.setMinimumSize(new java.awt.Dimension(400, 350));
        datosTicketListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosTicketListoMouseClicked(evt);
            }
        });

        jLabel6.setText("Datos del ticket atendido:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        botonDatosEnviar.setText("Enviar");
        botonDatosEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDatosEnviarMouseClicked(evt);
            }
        });
        botonDatosEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDatosEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosTicketListoLayout = new javax.swing.GroupLayout(datosTicketListo.getContentPane());
        datosTicketListo.getContentPane().setLayout(datosTicketListoLayout);
        datosTicketListoLayout.setHorizontalGroup(
            datosTicketListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosTicketListoLayout.createSequentialGroup()
                .addGroup(datosTicketListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonDatosEnviar)
                    .addGroup(datosTicketListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datosTicketListoLayout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jLabel6))
                        .addGroup(datosTicketListoLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        datosTicketListoLayout.setVerticalGroup(
            datosTicketListoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosTicketListoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botonDatosEnviar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tickets");

        jTextField1.setText("Usuario");

        jTextField2.setText("Contraseña");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        frameLogIn.setText("Log in");
        frameLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frameLogInMouseClicked(evt);
            }
        });
        frameLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(frameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(frameLogIn)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void frameLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameLogInMouseClicked
        // TODO add your handling code here:
        frameColores.setVisible(true);
       setVisible(false);
       client.initClient();
       client.send();
       
       frameColores.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            /*if (JOptionPane.showConfirmDialog(frameColores, 
                "¿Está seguro que desea cerrar esta ventana?", "Really Closing?", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                System.exit(0);
            }*/
            System.out.println(10/10);
            System.exit(0);
        }
    });
       
    }//GEN-LAST:event_frameLogInMouseClicked
    
    private void botonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAtenderActionPerformed

    private void botonRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRojoMouseClicked
        // TODO add your handling code here:
        frameTickets.setVisible(true);
    }//GEN-LAST:event_botonRojoMouseClicked

    private void botonAmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmarilloMouseClicked
        // TODO add your handling code here:
        frameTickets.setVisible(true);
    }//GEN-LAST:event_botonAmarilloMouseClicked

    private void botonVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerdeMouseClicked
        // TODO add your handling code here:
        frameTickets.setVisible(true);
    }//GEN-LAST:event_botonVerdeMouseClicked

    private void listTicketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listTicketsKeyPressed
        // TODO add your handling code here:
      //  datosTicket.add("Je, je", this);
      datosTicket.repaint();
      String ticketSeleccionado = listTickets.getSelectedValue();
        datosTicket.append(ticketSeleccionado);
        
    }//GEN-LAST:event_listTicketsKeyPressed

    private void listTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTicketsMouseClicked
        // TODO add your handling code here:
        
      String ticketSeleccionado = listTickets.getSelectedValue();
        datosTicket.setText(ticketSeleccionado);
    }//GEN-LAST:event_listTicketsMouseClicked

    private void botonAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtenderMouseClicked
        // TODO add your handling code here:
       javax.swing.Timer t;
       
       Cronometro.setVisible(true);
       
       
        
    }//GEN-LAST:event_botonAtenderMouseClicked

    private void botonAtendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAtendidoActionPerformed

    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseClicked
        // TODO add your handling code here:
        java.awt.Toolkit.getDefaultToolkit().beep();
        frameSinExito.setVisible(true);
        
       
    }//GEN-LAST:event_botonCancelarMouseClicked

    private void botonEnviarSinExitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviarSinExitoMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Enviado con éxito");
        frameSinExito.setVisible(false);
         Cronometro.setVisible(false);
         //frameTickets.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_botonEnviarSinExitoMouseClicked

    private void frameLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frameLogInActionPerformed

    private void botonDatosEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDatosEnviarActionPerformed

    private void datosTicketListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosTicketListoMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Enviado con éxito");
        
    }//GEN-LAST:event_datosTicketListoMouseClicked

    private void botonAtendidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtendidoMouseClicked
        // TODO add your handling code here:
        java.awt.Toolkit.getDefaultToolkit().beep();
        datosTicketListo.setVisible(true);
    }//GEN-LAST:event_botonAtendidoMouseClicked

    private void botonDatosEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDatosEnviarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Enviado con éxito");
        java.awt.Toolkit.getDefaultToolkit().beep();
        datosTicketListo.setVisible(false);
        Cronometro.setVisible(false);
    }//GEN-LAST:event_botonDatosEnviarMouseClicked

    private void botonDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDesconectarMouseClicked
        // TODO add your handling code here:
        frameColores.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_botonDesconectarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Cronometro;
    private javax.swing.JButton Pausar;
    private javax.swing.JButton Reanudar;
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonAtender;
    private javax.swing.JButton botonAtendido;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonDatosEnviar;
    private javax.swing.JButton botonDesconectar;
    private javax.swing.JButton botonEnviarSinExito;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton botonVerde;
    private javax.swing.JTextArea datosTicket;
    private javax.swing.JDialog datosTicketListo;
    private javax.swing.JFrame frameColores;
    private javax.swing.JButton frameLogIn;
    private javax.swing.JDialog frameSinExito;
    private javax.swing.JFrame frameTickets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> listTickets;
    // End of variables declaration//GEN-END:variables
}
