package Servidor;


import java.awt.Color;
import java.util.Collections;
import java.util.Locale;
import java.util.Vector;
import javax.swing.UIManager;
import java.awt.event.ActionListener;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CASA
 */
public class InterfazServidor extends javax.swing.JDialog {
    Server theServer = Server.getInstance();
    /**
     * Creates new form InterfazServidor
     */
    public InterfazServidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInServer = new javax.swing.JFrame();
        loginServer = new javax.swing.JButton();
        tabRojos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTicketsPendientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTicketsPendientes = new javax.swing.JTextArea();
        botonEnviarCola = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        colaRojos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoRojos = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        colaAmarillos = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        infoAmarillos = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        colaVerdes = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        infoVerdes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        desconectarServidor = new javax.swing.JButton();

        LogInServer.setMinimumSize(new java.awt.Dimension(400, 300));

        loginServer.setText("Conectar");
        loginServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginServerMouseClicked(evt);
            }
        });
        loginServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInServerLayout = new javax.swing.GroupLayout(LogInServer.getContentPane());
        LogInServer.getContentPane().setLayout(LogInServerLayout);
        LogInServerLayout.setHorizontalGroup(
            LogInServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInServerLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(loginServer)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        LogInServerLayout.setVerticalGroup(
            LogInServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInServerLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(loginServer)
                .addGap(73, 73, 73))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabRojos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tabRojos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabRojosMouseClicked(evt);
            }
        });

        listaTicketsPendientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTicketsPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTicketsPendientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaTicketsPendientes);

        infoTicketsPendientes.setEditable(false);
        infoTicketsPendientes.setColumns(20);
        infoTicketsPendientes.setRows(5);
        jScrollPane2.setViewportView(infoTicketsPendientes);

        botonEnviarCola.setText("Enviar a cola");
        botonEnviarCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEnviarColaMouseClicked(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEnviarCola)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnviarCola)
                    .addComponent(botonActualizar)))
        );

        tabRojos.addTab("INBOX", jPanel1);

        colaRojos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colaRojosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(colaRojos);

        infoRojos.setEditable(false);
        infoRojos.setColumns(20);
        infoRojos.setRows(5);
        jScrollPane4.setViewportView(infoRojos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tabRojos.addTab("Rojos", jPanel3);

        colaAmarillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colaAmarillosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(colaAmarillos);

        infoAmarillos.setEditable(false);
        infoAmarillos.setColumns(20);
        infoAmarillos.setRows(5);
        jScrollPane7.setViewportView(infoAmarillos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        tabRojos.addTab("Amarillos", jPanel4);

        colaVerdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colaVerdesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(colaVerdes);

        infoVerdes.setEditable(false);
        infoVerdes.setColumns(20);
        infoVerdes.setRows(5);
        jScrollPane8.setViewportView(infoVerdes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        tabRojos.addTab("Verdes", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        desconectarServidor.setText("Desconectar");
        desconectarServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desconectarServidorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addComponent(tabRojos)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desconectarServidor))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabRojos, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desconectarServidor)
                .addContainerGap())
        );

        tabRojos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaTicketsPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTicketsPendientesMouseClicked
        // TODO add your handling code here:
      //  listaTicketsPendientes.getSelectedIndices();
       // listaTicketsPendientes.getSelectedIndex();
       // listaTicketsPendientes.getMaxSelectionIndex();
        //listaTicketsPendientes.isSelectedIndex(WIDTH);
        
        //String ticketSeleccionado = listaTicketsPendientes.getSelectedValuesList().get(listaTicketsPendientes.getMaxSelectionIndex());
        String ticketSeleccionado = listaTicketsPendientes.getSelectedValue();
        Ticket eticket = theServer.getTicketWString(ticketSeleccionado);
        infoTicketsPendientes.setText("ID del ticket: " + eticket.getTicketID() + "\n" + 
                "Fecha de recibido: " + eticket.getTimeReceived() + "\n" +
                "Asunto: " + ticketSeleccionado + "\n"
        + "Estado: " + eticket.getTicketStatusStr());
        //infoTicketsPendientes
        //Object value;
        //getListCellRendererComponent( listaTicketsPendientes, value, index, isSelected, cellHasFocus );
        //listaTicketsPendientes.getSelectedValuesList().get(0)
       // listaTicketsPendientes.getComponent(0).setBackground(Color.black);
       if (listaTicketsPendientes.getSelectionBackground() == UIManager.getColor("Panel.background")){
            listaTicketsPendientes.setSelectionBackground(Color.GREEN);
            botonEnviarCola.setText("Enviar a cola verde");
        }
       else if (listaTicketsPendientes.getSelectionBackground() == Color.GREEN){
            listaTicketsPendientes.setSelectionBackground(Color.yellow);
            botonEnviarCola.setText("Enviar a cola amarilla");
        }
        else if (listaTicketsPendientes.getSelectionBackground() == Color.yellow){
            listaTicketsPendientes.setSelectionBackground(Color.red);
            botonEnviarCola.setText("Enviar a cola roja");
        }
        else if (listaTicketsPendientes.getSelectionBackground() == Color.yellow){
            listaTicketsPendientes.setSelectionBackground(Color.green);
        }
        else{
            listaTicketsPendientes.setSelectionBackground(UIManager.getColor("Panel.background"));
        }
        
        
    }//GEN-LAST:event_listaTicketsPendientesMouseClicked
    void addListener(ActionListener listener){
        
    }
    private void botonEnviarColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviarColaMouseClicked
        // TODO add your handling code here:
        //listaTicketsPendientes.getSelectionModel().
        if (botonEnviarCola.getText() == "Enviar a cola"){
            return;
        }
        Vector<Ticket> vectorTickets = theServer.getAllTickets();
        
        java.util.List<String> listaTickets = listaTicketsPendientes.getSelectedValuesList();
        //botonEnviarCola.addActionListener(l);
        
        javax.swing.DefaultListModel<String> listaTicketString =  new javax.swing.DefaultListModel<String>();
        
        int largo = listaTickets.size();
        if (largo>0) {
            for (int i = 0; i < largo; i++) {
                if (botonEnviarCola.getText() == "Enviar a cola verde"){
                    theServer.setTicketCategoryWString(listaTickets.get(i), "Leve");
                    
     
                }
                else if (botonEnviarCola.getText() == "Enviar a cola amarilla"){
                    theServer.setTicketCategoryWString(listaTickets.get(i), "Media");
                    
                }
                else if (botonEnviarCola.getText() == "Enviar a cola roja"){
                    theServer.setTicketCategoryWString(listaTickets.get(i), "Urgente");
                }
               theServer.getTicketWString(listaTickets.get(i)).setTicketStatus("En cola");
               listaTicketString.addElement(listaTickets.get(i));
                
            }
        }
        
        
        if (botonEnviarCola.getText() == "Enviar a cola verde"){
        colaVerdes.setModel(listaTicketString);
        }
        else if (botonEnviarCola.getText() == "Enviar a cola amarilla"){
        colaAmarillos.setModel(listaTicketString);
        }
        else if (botonEnviarCola.getText() == "Enviar a cola roja"){
        colaRojos.setModel(listaTicketString);
        }
        this.tabRojosMouseClicked(evt);
        
    }//GEN-LAST:event_botonEnviarColaMouseClicked

    private void loginServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginServerMouseClicked
        // TODO add your handling code here:
        
        System.out.println("AAAAAAAAAAAAH");
        Server s = Server.getInstance();
        //SocketThread socket = new SocketThread(this, s);
        
        //s.initServer(socket);
        
        Server server = Server.getInstance();
    
        
        server.initServer(this);
        Vector<Ticket> vectorTickets = theServer.getAllTickets();
        
        //java.util.List<String> listaTickets = listaTicketsPendientes.getSelectedValuesList();
        //botonEnviarCola.addActionListener(l);
        
        javax.swing.DefaultListModel<String> listaTicketString =  new javax.swing.DefaultListModel<String>();
        
        int largo = vectorTickets.size();
        if (largo>0) {
            for (int i = 0; i < largo; i++) {
               listaTicketString.addElement(vectorTickets.get(i).getSubject());
                
            }
        }
        listaTicketsPendientes.setModel(listaTicketString);
        setVisible(true);
    }//GEN-LAST:event_loginServerMouseClicked

    private void loginServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginServerActionPerformed

    private void botonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonActualizarMouseClicked

    private void tabRojosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabRojosMouseClicked
        // TODO add your handling code here:
        Vector<Ticket> vectorTickets = theServer.getAllTickets();
        
        //java.util.List<String> listaTickets = listaTicketsPendientes.getSelectedValuesList();
        //botonEnviarCola.addActionListener(l);
        
        javax.swing.DefaultListModel<String> listaTicketString =  new javax.swing.DefaultListModel<String>();
        
        int largo = vectorTickets.size();
        if (largo>0) {
            for (int i = 0; i < largo; i++) {
               if (vectorTickets.get(i).getTicketStatus() == TicketStatus.PENDING){
                    listaTicketString.addElement(vectorTickets.get(i).getSubject());
               }
            }
        }
        listaTicketsPendientes.setModel(listaTicketString);
        
    }//GEN-LAST:event_tabRojosMouseClicked

    private void colaRojosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colaRojosMouseClicked
        // TODO add your handling code here:
        String ticketSeleccionado = colaRojos.getSelectedValue();
        Ticket eticket = theServer.getTicketWString(ticketSeleccionado);
        infoRojos.setText("ID del ticket: " + eticket.getTicketID() + "\n" + 
                "Fecha de recibido: " + eticket.getTimeReceived() + "\n" +
                "Asunto: " + ticketSeleccionado + "\n"
        + "Estado: " + eticket.getTicketStatusStr());
    }//GEN-LAST:event_colaRojosMouseClicked

    private void colaAmarillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colaAmarillosMouseClicked
        // TODO add your handling code here:
        String ticketSeleccionado = colaAmarillos.getSelectedValue();
        Ticket eticket = theServer.getTicketWString(ticketSeleccionado);
        infoAmarillos.setText("ID del ticket: " + eticket.getTicketID() + "\n" + 
                "Fecha de recibido: " + eticket.getTimeReceived() + "\n" +
                "Asunto: " + ticketSeleccionado + "\n"
        + "Estado: " + eticket.getTicketStatusStr());
    }//GEN-LAST:event_colaAmarillosMouseClicked

    private void colaVerdesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colaVerdesMouseClicked
        // TODO add your handling code here:
        String ticketSeleccionado = colaVerdes.getSelectedValue();
        Ticket eticket = theServer.getTicketWString(ticketSeleccionado);
        infoVerdes.setText("ID del ticket: " + eticket.getTicketID() + "\n" + 
                "Fecha de recibido: " + eticket.getTimeReceived() + "\n" +
                "Asunto: " + ticketSeleccionado + "\n"
        + "Estado: " + eticket.getTicketStatusStr());
        
    }//GEN-LAST:event_colaVerdesMouseClicked

    private void desconectarServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desconectarServidorMouseClicked
        // TODO add your handling code here:
        theServer.saveExcel();
        theServer.closeSocket();
        
        setVisible(false);
    }//GEN-LAST:event_desconectarServidorMouseClicked

    /**
     * @param args the command line arguments
     */
  /* public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazServidor dialog = new InterfazServidor(new javax.swing.JFrame(), true);
                Server server = new Server();
        server.initServer();
        SocketThread socket = new SocketThread(dialog, server);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFrame LogInServer;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEnviarCola;
    private javax.swing.JList<String> colaAmarillos;
    private javax.swing.JList<String> colaRojos;
    private javax.swing.JList<String> colaVerdes;
    private javax.swing.JButton desconectarServidor;
    private javax.swing.JTextArea infoAmarillos;
    private javax.swing.JTextArea infoRojos;
    private javax.swing.JTextArea infoTicketsPendientes;
    private javax.swing.JTextArea infoVerdes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JList<String> listaTicketsPendientes;
    private javax.swing.JButton loginServer;
    private javax.swing.JTabbedPane tabRojos;
    // End of variables declaration//GEN-END:variables
}
